export const dummyMoviesData = [
  {
    name: 'Top Gun: Maverick',
    description:
      "After more than thirty years of service as one of the Navy's top aviators, Pete Mitchell is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank that would ground him.",
    group: 'Trending Movies',
    type: 'Action',
    coverPhoto: 'topgunmaverick.jpg',
    photo: 'topgunmaverick.jpg',
    releaseYear: 2022,
    imdbRating: 8.5,
  },
  {
    name: 'Avatar: The Way of Water',
    description:
      "Jake Sully lives with his newfound family formed on the planet of Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their planet.",
    group: 'Trending Movies',
    type: 'Sci-Fi',
    coverPhoto: 'avatar.jpg',
    photo: 'avatarthewayofwater.jpg',
    releaseYear: 2022,
    imdbRating: 8.9,
  },
  {
    name: 'Prey',
    description:
      'The origin story of the Predator in the world of the Comanche Nation 300 years ago. Naru, a skilled warrior, fights to protect her tribe against one of the first highly-evolved Predators to land on Earth.',
    group: 'Trending Movies',
    type: 'Hulu',
    coverPhoto: 'prey.jpg',
    photo: 'prey.jpg',
    releaseYear: 2022,
    imdbRating: 7.2,
  },
  {
    name: 'Nope',
    description:
      'The residents of a lonely gulch in inland California bear witness to an uncanny and chilling discovery.',
    group: 'Trending Movies',
    type: 'Technology',
    coverPhoto: 'nope.jpg',
    photo: 'nope.jpg',
    releaseYear: 2022,
    imdbRating: 7.3,
  },
  {
    name: 'Bullet Train',
    description:
      'Five assassins aboard a fast moving bullet train find out their missions have something in common.',
    group: 'Trending Movies',
    type: 'Hollywood',
    coverPhoto: 'bullettrain.jpg',
    photo: 'bullettrain.jpg',
    releaseYear: 2022,
    imdbRating: 7.5,
  },
  {
    name: 'Thor: Love and Thunder',
    description:
      'Thor enlists the help of Valkyrie, Korg and ex-girlfriend Jane Foster to fight Gorr the God Butcher, who intends to make the gods extinct.',
    group: 'Trending Movies',
    type: 'Marvel',
    coverPhoto: 'thorloveandthunder.jpg',
    photo: 'thorloveandthunder.jpg',
    releaseYear: 2022,
    imdbRating: 6.7,
  },
  {
    name: 'Black Adam',
    description:
      'Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods-and imprisoned just as quickly-Black Adam (Johnson) is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.',
    group: 'Trending Movies',
    type: 'Superhero',
    coverPhoto: 'blackadam.jpg',
    photo: 'blackadam.jpg',
    releaseYear: 2022,
    imdbRating: 6.7,
  },
  {
    name: "The King's Man",
    description:
      'In the early years of the 20th century, the Kingsman agency is formed to stand against a cabal plotting a war to wipe out millions.',
    group: 'Trending Movies',
    type: 'Disney',
    coverPhoto: 'thekingsman.jpg',
    photo: 'kingsman.jpg',
    releaseYear: 2022,
    imdbRating: 6.3,
  },
  {
    name: 'Purple Hearts',
    description:
      'In spite of their many differences, Cassie, a struggling singer-songwriter, and Luke, a troubled Marine, agree to marry solely for military benefits. But when tragedy strikes, the line between real and pretend begins to blur.',
    group: 'Trending Movies',
    type: 'Netflix',
    coverPhoto: 'purplehearts.jpg',
    photo: 'purplehearts.jpg',
    releaseYear: 2022,
    imdbRating: 6.8,
  },
  {
    name: 'The Sea Beast',
    description:
      'When a young girl stows away on the ship of a legendary sea monster hunter, they launch an epic journey into uncharted waters - and make history to boot.',
    group: 'Trending Movies',
    type: 'Animation',
    coverPhoto: 'theseabeast.jpg',
    photo: 'seabeast.webp',
    releaseYear: 2022,
    imdbRating: 7.1,
  },
  {
    name: 'Secret Headquarters',
    description:
      "While hanging out after school, Charlie and his friends discover the headquarters of the world's most powerful superhero hidden beneath his home. When villains attack, they must team up to defend the headquarters and save the world.",
    group: 'Trending Movies',
    type: 'Adventure',
    coverPhoto: 'secretheadquarters.jpg',
    photo: 'secretheadquarters.jpg',
    releaseYear: 2022,
    imdbRating: 4.9,
  },
  {
    name: 'The Dark Knight',
    description:
      'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    group: 'Top Rated',
    type: 'Action',
    coverPhoto: 'thedarkknight.jpg',
    photo: 'darkknight.jpg',
    releaseYear: 2008,
    imdbRating: 9.0,
  },
  {
    name: 'The Lord of the Rings: The Return of the King',
    description:
      "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    group: 'Top Rated',
    type: 'Adventure',
    coverPhoto: 'lordoftherings.jpg',
    photo: 'lordoftherings.jpg',
    releaseYear: 2003,
    imdbRating: 9.0,
  },
  {
    name: 'Interstellar',
    description:
      "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    group: 'Top Rated',
    type: 'Sci-Fi',
    coverPhoto: 'interstellar.jpg',
    photo: 'intersteller.webp',
    releaseYear: 2014,
    imdbRating: 8.6,
  },
  {
    name: 'Parasite',
    description:
      'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    group: 'Top Rated',
    type: 'Hulu',
    coverPhoto: 'parasite.jpg',
    photo: 'parasite.jpg',
    releaseYear: 2019,
    imdbRating: 8.5,
  },
  {
    name: 'Minority Report',
    description:
      'In a future where a special police unit is able to arrest murderers before they commit their crimes, an officer from that unit is himself accused of a future murder.',
    group: 'Top Rated',
    type: 'Technology',
    coverPhoto: 'minorityreport.jpg',
    photo: 'minorityreport.jpg',
    releaseYear: 2002,
    imdbRating: 7.7,
  },
  {
    name: 'Shutter Island',
    description:
      'In 1954, a U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane.',
    group: 'Top Rated',
    type: 'Hollywood',
    coverPhoto: 'shutterisland.jpg',
    photo: 'shutterisland.jpg',
    releaseYear: 2010,
    imdbRating: 8.2,
  },
  {
    name: 'Avengers: Infinity War',
    description:
      'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.',
    group: 'Top Rated',
    type: 'Marvel',
    coverPhoto: 'infinitywar.jpg',
    photo: 'infinitywar.jpg',
    releaseYear: 2018,
    imdbRating: 8.4,
  },
  {
    name: 'Logan',
    description:
      'In a future where mutants are nearly extinct, an elderly and weary Logan leads a quiet life. But when Laura, a mutant child pursued by scientists, comes to him for help, he must get her to safety.',
    group: 'Top Rated',
    type: 'Superhero',
    coverPhoto: 'logan.jpg',
    photo: 'logan.jpg',
    releaseYear: 2017,
    imdbRating: 8.1,
  },
  {
    name: 'Ratatouille',
    description:
      'A rat who can cook makes an unusual alliance with a young kitchen worker at a famous Paris restaurant.',
    group: 'Top Rated',
    type: 'Disney',
    coverPhoto: 'ratatouile.jpg',
    photo: 'ratatoulle.jpg',
    releaseYear: 2007,
    imdbRating: 8.1,
  },
  {
    name: 'The Adam Project',
    description:
      'After accidentally crash-landing in 2022, time-traveling fighter pilot Adam Reed teams up with his 12-year-old self for a mission to save the future.',
    group: 'Top Rated',
    type: 'Netflix',
    coverPhoto: 'theadamproject.jpg',
    photo: 'theadamproject.jpg',
    releaseYear: 2022,
    imdbRating: 6.7,
  },
  {
    name: 'The Adventures of Tintin',
    description:
      "Intrepid reporter Tintin and Captain Haddock set off on a treasure hunt for a sunken ship commanded by Haddock's ancestor.",
    group: 'Top Rated',
    type: 'Animation',
    coverPhoto: 'adventuresoftintin.jpg',
    photo: 'theadventureoftintin.jpg',
    releaseYear: 2011,
    imdbRating: 7.3,
  },
  {
    name: 'Free Guy',
    description:
      "A bank teller discovers that he's actually an NPC inside a brutal, open world video game.",
    group: 'Comedy Movies',
    type: 'Action',
    coverPhoto: 'feeguy.jpg',
    photo: 'freeguy.jpg',
    releaseYear: 2021,
    imdbRating: 7.1,
  },
  {
    name: 'Journey 2: The Mysterious Island',
    description:
      "Sean Anderson partners with his mom's husband on a mission to find his grandfather, who is thought to be missing on a mythical island.",
    group: 'Comedy Movies',
    type: 'Adventure',
    coverPhoto: 'journey2themysteriousisland.jpg',
    photo: 'journey2mysteriousisland.jpg',
    releaseYear: 2012,
    imdbRating: 5.7,
  },
  {
    name: "The World's End",
    description:
      "Five friends who reunite in an attempt to top their epic pub crawl from twenty years earlier unwittingly become humanity's only hope for survival.",
    group: 'Comedy Movies',
    type: 'Sci-Fi',
    coverPhoto: 'theworldsend.jpg',
    photo: 'theworldsend.jpg',
    releaseYear: 2013,
    imdbRating: 6.9,
  },
  {
    name: 'Booksmart',
    description:
      'On the eve of their high-school graduation, two academic superstars and best friends realize they should have worked less and played more. Determined not to fall short of their peers, the girls try to cram four years of fun into one night.',
    group: 'Comedy Movies',
    type: 'Hulu',
    coverPhoto: 'booksmart.jpg',
    photo: 'booksmart.webp',
    releaseYear: 2019,
    imdbRating: 7.1,
  },
  {
    name: 'The Mitchells vs. the Machines',
    description:
      "A quirky, dysfunctional family's road trip is upended when they find themselves in the middle of the robot apocalypse and suddenly become humanity's unlikeliest last hope.",
    group: 'Comedy Movies',
    type: 'Technology',
    coverPhoto: 'mitchellsvsthemachines.jpg',
    photo: 'mitchellsvsthemachines.jpg',
    releaseYear: 2021,
    imdbRating: 7.6,
  },
  {
    name: 'The Dictator',
    description:
      'The heroic story of a dictator who risked his life to ensure that democracy would never come to the country he so lovingly oppressed.',
    group: 'Comedy Movies',
    type: 'Hollywood',
    coverPhoto: 'thedictator.jpg',
    photo: 'thedictator.jpg',
    releaseYear: 2012,
    imdbRating: 6.4,
  },
  {
    name: 'Deadpool',
    description:
      'A wisecracking mercenary gets experimented on and becomes immortal but ugly, and sets out to track down the man who ruined his looks.',
    group: 'Comedy Movies',
    type: 'Marvel',
    coverPhoto: 'deadpool.jpg',
    photo: 'deadpool.jpg',
    releaseYear: 2016,
    imdbRating: 8.0,
  },
  {
    name: 'Shazam!',
    description:
      'A newly fostered young boy in search of his mother instead finds unexpected super powers and soon gains a powerful enemy.',
    group: 'Comedy Movies',
    type: 'Superhero',
    coverPhoto: 'shazam.jpg',
    photo: 'shazam.jpg',
    releaseYear: 2019,
    imdbRating: 7.0,
  },
  {
    name: 'The Muppets',
    description:
      'A Muppet fanatic with some help from his 2 human compatriots must regroup the Muppet gang to stop an avaricious oil mogul from taking down one of their precious life-longing treasures.',
    group: 'Comedy Movies',
    type: 'Disney',
    coverPhoto: 'themuppets.jpg',
    photo: 'themuppetmovie.jpg',
    releaseYear: 2011,
    imdbRating: 7.1,
  },
  {
    name: 'Johnny English Reborn',
    description:
      'Johnny English goes up against international assassins hunting down Chinese Premier Xiang Ping.',
    group: 'Comedy Movies',
    type: 'Netflix',
    coverPhoto: 'johnnyenglishreborn.jpg',
    photo: 'johnnyenglishrebordn.jpg',
    releaseYear: 2011,
    imdbRating: 6.3,
  },
  {
    name: 'Minions',
    description:
      'Minions Stuart, Kevin, and Bob are recruited by Scarlet Overkill, a supervillain who, alongside her inventor husband Herb, hatches a plot to take over the world.',
    group: 'Comedy Movies',
    type: 'Animation',
    coverPhoto: 'minions.jpg',
    photo: 'minions.jpg',
    releaseYear: 2015,
    imdbRating: 6.4,
  },
  {
    name: 'Wonder Woman',
    description:
      'When a pilot crashes and tells of conflict in the outside world, Diana, an Amazonian warrior in training, leaves home to fight a war, discovering her full powers and true destiny.',
    group: 'Romance Movies',
    type: 'Action',
    coverPhoto: 'wonderwoman.jpg',
    photo: 'wonderwoman.jpg',
    releaseYear: 2020,
    imdbRating: 7.4,
  },
  {
    name: 'Pirates of the Caribbean: The Curse of the Black Pearl',
    description:
      "Blacksmith Will Turner teams up with eccentric pirate 'Captain' Jack Sparrow to save his love, the governor's daughter, from Jack's former pirate allies, who are now undead.",
    group: 'Romance Movies',
    type: 'Adventure',
    coverPhoto: 'piratesofthecarribbean.jpg',
    photo: 'piratesofthecarribean.jpg',
    releaseYear: 2003,
    imdbRating: 8.1,
  },
  {
    name: "The Time Traveler's Wife",
    description:
      'Tells the intricate love story of Clare and Henry, and a marriage with a problem... time travel.',
    group: 'Romance Movies',
    type: 'Sci-Fi',
    coverPhoto: 'timetravellerswife.jpg',
    photo: 'thetimetravellerswife.jpg',
    releaseYear: 2009,
    imdbRating: 7.7,
  },
  {
    name: 'Palm Springs',
    description:
      'Stuck in a time loop, two wedding guests develop a budding romance while living the same day over and over again.',
    group: 'Romance Movies',
    type: 'Hulu',
    coverPhoto: 'palmsprings.jpg',
    photo: 'palmsprings.jpg',
    releaseYear: 2020,
    imdbRating: 7.4,
  },
  {
    name: 'Wall-E',
    description:
      'In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.',
    group: 'Romance Movies',
    type: 'Technology',
    coverPhoto: 'walle.jpg',
    photo: 'walle.jpg',
    releaseYear: 2008,
    imdbRating: 8.4,
  },
  {
    name: 'La La Land',
    description:
      'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.',
    group: 'Romance Movies',
    type: 'Hollywood',
    coverPhoto: 'lalaland.jpg',
    photo: 'lalaland.jpg',
    releaseYear: 2016,
    imdbRating: 8.0,
  },
  {
    name: 'Ant-Man and the Wasp',
    description:
      'As Scott Lang balances being both a superhero and a father, Hope van Dyne and Dr. Hank Pym present an urgent new mission that finds the Ant-Man fighting alongside The Wasp to uncover secrets from their past.',
    group: 'Romance Movies',
    type: 'Marvel',
    coverPhoto: 'antmanandthewasp.jpg',
    photo: 'antmanandthewasp.jpg',
    releaseYear: 2018,
    imdbRating: 7.0,
  },
  {
    name: 'The Darkest Minds',
    description:
      'Imprisoned by an adult world that now fears everyone under 18, a group of teens form a resistance group to fight back and reclaim control of their future.',
    group: 'Romance Movies',
    type: 'Superhero',
    coverPhoto: 'thedarkestminds.jpg',
    photo: 'thedarkestminds.jpg',
    releaseYear: 2018,
    imdbRating: 5.7,
  },
  {
    name: 'Beauty and the Beast',
    description:
      'A selfish Prince is cursed to become a monster for the rest of his life, unless he learns to fall in love with a beautiful young woman he keeps prisoner.',
    group: 'Romance Movies',
    type: 'Disney',
    coverPhoto: 'beautyandthebeast.jpg',
    photo: 'beautyandthebeast.jpg',
    releaseYear: 2017,
    imdbRating: 7.1,
  },
  {
    name: 'The Kissing Booth',
    description:
      'A high school student is forced to confront her secret crush at a kissing booth.',
    group: 'Romance Movies',
    type: 'Netflix',
    coverPhoto: 'thekissingbooth.jpg',
    photo: 'thekissingbooth.jpg',
    releaseYear: 2018,
    imdbRating: 5.9,
  },
  {
    name: 'Shrek',
    description:
      'A mean lord exiles fairytale creatures to the swamp of a grumpy ogre, who must go on a quest and rescue a princess for the lord in order to get his land back.',
    group: 'Romance Movies',
    type: 'Animation',
    coverPhoto: 'shrek.jpg',
    photo: 'shrek.jpg',
    releaseYear: 2001,
    imdbRating: 7.9,
  },
  {
    name: 'Train To Busan',
    description:
      'While a zombie virus breaks out in South Korea, passengers struggle to survive on the train from Seoul to Busan.',
    group: 'Horror Movies',
    type: 'Action',
    coverPhoto: 'traintobusan.jpg',
    photo: 'traintobusan.jpg',
    releaseYear: 2016,
    imdbRating: 7.6,
  },
  {
    name: 'The Mummy',
    description:
      'An ancient Egyptian princess is awakened from her crypt beneath the desert, bringing with her malevolence grown over millennia, and terrors that defy human comprehension.',
    group: 'Horror Movies',
    type: 'Adventure',
    coverPhoto: 'themummy.jpg',
    photo: 'themummy.jpg',
    releaseYear: 2017,
    imdbRating: 5.4,
  },
  {
    name: 'Annihilation',
    description:
      "A biologist signs up for a dangerous, secret expedition into a mysterious zone where the laws of nature don't apply.",
    group: 'Horror Movies',
    type: 'Sci-Fi',
    coverPhoto: 'annihilation.jpg',
    photo: 'annihilation.jpg',
    releaseYear: 2018,
    imdbRating: 6.8,
  },
  {
    name: 'Black Swan',
    description:
      "A committed dancer struggles to maintain her sanity after winning the lead role in a production of Tchaikovsky's 'Swan Lake'.",
    group: 'Horror Movies',
    type: 'Hulu',
    coverPhoto: 'blackswan.jpg',
    photo: 'blackswan.jpg',
    releaseYear: 2010,
    imdbRating: 8.0,
  },
  {
    name: 'Unfriended: Dark Web',
    description:
      'A teen comes into possession of a new laptop and soon discovers that the previous owner is not only watching him, but will also do anything to get it back.',
    group: 'Horror Movies',
    type: 'Technology',
    coverPhoto: 'unfriendeddarkweb.jpg',
    photo: 'unfriendeddarkweb.jpg',
    releaseYear: 2018,
    imdbRating: 6.0,
  },
  {
    name: 'The Conjuring',
    description:
      'Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.',
    group: 'Horror Movies',
    type: 'Hollywood',
    coverPhoto: 'theconjuring.jpg',
    photo: 'theconjuring.jpg',
    releaseYear: 2013,
    imdbRating: 7.5,
  },
  {
    name: 'Ghost Rider',
    description:
      "When motorcycle rider Johnny Blaze sells his soul to the Devil to save his father's life, he is transformed into the Ghost Rider, the Devil's own bounty hunter, and is sent to hunt down sinners.",
    group: 'Horror Movies',
    type: 'Marvel',
    coverPhoto: 'ghostrider.jpg',
    photo: 'ghostrider.jpg',
    releaseYear: 2007,
    imdbRating: 5.2,
  },
  {
    name: 'The New Mutants',
    description:
      'Five young mutants, just discovering their abilities while held in a secret facility against their will, fight to escape their past sins and save themselves.',
    group: 'Horror Movies',
    type: 'Superhero',
    coverPhoto: 'thenewmutants.jpg',
    photo: 'thenewmutants.jpg',
    releaseYear: 2020,
    imdbRating: 5.3,
  },
  {
    name: 'Frankenweenie',
    description:
      "When a boy's beloved dog passes away suddenly, he attempts to bring the animal back to life through a powerful science experiment.",
    group: 'Horror Movies',
    type: 'Disney',
    coverPhoto: 'frankenweenie.jpg',
    photo: 'frankenweenie.jpg',
    releaseYear: 2012,
    imdbRating: 6.9,
  },
  {
    name: 'The Silence',
    description:
      'When the world is under attack from terrifying creatures who hunt their human prey by sound, 16-year old Ally Andrews (Kiernan Shipka), who lost her hearing at 13, and her family seek refuge in a remote haven.',
    group: 'Horror Movies',
    type: 'Netflix',
    coverPhoto: 'thesilence.jpg',
    photo: 'thesilence.jpg',
    releaseYear: 2019,
    imdbRating: 5.3,
  },
  {
    name: 'Coraline',
    description:
      'An adventurous 11-year-old girl finds another world that is a strangely idealized version of her frustrating home, but it has sinister secrets.',
    group: 'Horror Movies',
    type: 'Animation',
    coverPhoto: 'coraline.jpg',
    photo: 'coraline.jpg',
    releaseYear: 2009,
    imdbRating: 7.7,
  },
  {
    name: 'Racing Extinction',
    description:
      'A documentary that follows undercover activists trying to stave off a man-made mass extinction.',
    group: 'Documentaries Movies',
    type: 'Action',
    coverPhoto: 'racingextinction.jpg',
    photo: 'racingextinction.jpg',
    releaseYear: 2015,
    imdbRating: 8.2,
  },
  {
    name: 'Touching the Void',
    description:
      'The true story of two climbers and their perilous journey up the west face of Siula Grande in the Peruvian Andes in 1985.',
    group: 'Documentaries Movies',
    type: 'Adventure',
    coverPhoto: 'touchingthevoid.jpg',
    photo: 'touchingthevoid.jpg',
    releaseYear: 2003,
    imdbRating: 8.0,
  },
  {
    name: 'Alien Planet',
    description:
      "The CGI or computer animated drama/documentary takes place on Darwin IV, a planet 6.5 light years from earth, with 2 suns and 60% of Earth's gravity. Having identified Darwin as a world that could support life, Earth sends a pilot mission consisting of the Mothership Von Braun and three probes: Balboa, Da Vinci, and Newton. This robotic fleet is responsible for finding and assessing any life forms on Darwin IV. Initially, the expectation is to find microscopic life, but the probes soon find themselves in the middle of a developed ecosystem teeming with diversity of life of all sizes. The drama on Darwin IV is motivated by real science missions, such as the NASA Origins Program and the NASA / JPL Planet-Finder Mission, as well as the European Space Agency's Darwin Project. 'Alien Planet' is a cosmic expedition along side Stephen Hawking, Michio Kaku, Jack Horner, Craig Venter, and George Lucas, and NASA's Chief Scientist Jim Garvin. No longer just the domain of science fiction, 'Alien Planet' dramatizes an exciting and possible answer to what alien life really looks like and when we'll find it.",
    group: 'Documentaries Movies',
    type: 'Sci-Fi',
    coverPhoto: 'alienplanet.jpg',
    photo: 'alienplanet.jpg',
    releaseYear: 2005,
    imdbRating: 7.2,
  },
  {
    name: 'Arctic Tale',
    description:
      'Two narratives -- the life cycle of a mother walrus and her calf, and the life of a polar bear and her cubs -- are used to illustrate the harsh realities of existence in the Arctic.',
    group: 'Documentaries Movies',
    type: 'Hulu',
    coverPhoto: 'arctictale.jpg',
    photo: 'arctictale.jpg',
    releaseYear: 2014,
    imdbRating: 6.9,
  },
  {
    name: 'The Social Dilemma',
    description:
      'Explores the dangerous human impact of social networking, with tech experts sounding the alarm on their own creations.',
    group: 'Documentaries Movies',
    type: 'Technology',
    coverPhoto: 'thesocialdilema.webp',
    photo: 'thesocialdilema.jpg',
    releaseYear: 2020,
    imdbRating: 7.6,
  },
  {
    name: 'Free Solo',
    description:
      'Alex Honnold attempts to become the first person to ever free solo climb El Capitan.',
    group: 'Documentaries Movies',
    type: 'Hollywood',
    coverPhoto: 'freesolo.jpg',
    photo: 'freesolo.jpg',
    releaseYear: 2018,
    imdbRating: 8.1,
  },
  {
    name: 'Marvel Studios: Assembled',
    description:
      "Assembled is a comprehensive documentary series that chronicles the creation of Marvel Studios' thrilling new shows and theatrical releases. Assembled is an immersive, and in-depth examination of the next phase of the MCU.",
    group: 'Documentaries Movies',
    type: 'Marvel',
    coverPhoto: 'marvelstudiosassembled.jpg',
    photo: 'marvelstudioassembled.jpg',
    releaseYear: 2021,
    imdbRating: 7.9,
  },
  {
    name: 'Superheroes',
    description:
      'A journey inside the world of real life caped crusaders. From all over America, these self-proclaimed crime fighters, don masks, homemade costumes and elaborate utility belts in an attempt to bring justice to evildoers everywhere.',
    group: 'Documentaries Movies',
    type: 'Superhero',
    coverPhoto: 'superheroes.jpg',
    photo: 'superheroes.webp',
    releaseYear: 2011,
    imdbRating: 6.4,
  },
  {
    name: 'Waking Sleeping Beauty',
    description:
      "The story of the Disney Renaissance, an incredibly prolific, successful and prestigious decade lasting from 1984 to 1994 that saw the fallen Walt Disney Animation Studios' unexpected progressive triumphant return to excellence.",
    group: 'Documentaries Movies',
    type: 'Disney',
    coverPhoto: 'wakingsleepingbeauty.jpg',
    photo: 'wakingsleepingbeauty.jpg',
    releaseYear: 2009,
    imdbRating: 7.6,
  },
  {
    name: 'The Great Hack',
    description:
      'The Cambridge Analytica scandal is examined through the roles of several affected persons.',
    group: 'Documentaries Movies',
    type: 'Netflix',
    coverPhoto: 'thegreathack.webp',
    photo: 'thegreathack.jpg',
    releaseYear: 2019,
    imdbRating: 7.0,
  },
  {
    name: 'Flee',
    description:
      'FLEE tells the extraordinary true story of a man, Amin, on the verge of marriage which compels him to reveal his hidden past for the first time.',
    group: 'Documentaries Movies',
    type: 'Animation',
    coverPhoto: 'flee.jpg',
    photo: 'flee.jpg',
    releaseYear: 2021,
    imdbRating: 7.9,
  },
  {
    name: 'Inception',
    description:
      'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.',
    group: 'Popular Movies',
    type: 'Action',
    coverPhoto: 'inception.jpg',
    photo: 'inception.jpg',
    releaseYear: 2010,
    imdbRating: 8.8,
  },
  {
    name: 'The Lost City',
    description:
      'A reclusive romance novelist on a book tour with her cover model gets swept up in a kidnapping attempt that lands them both in a cutthroat jungle adventure.',
    group: 'Popular Movies',
    type: 'Adventure',
    coverPhoto: 'thelostcity.jpg',
    photo: 'thelostcity.jpg',
    releaseYear: 2022,
    imdbRating: 6.1,
  },
  {
    name: 'Blade Runner 2049',
    description:
      "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
    group: 'Popular Movies',
    type: 'Sci-Fi',
    coverPhoto: 'bladerunner.jpg',
    photo: 'bladerunner.jpg',
    releaseYear: 2017,
    imdbRating: 8.0,
  },
  {
    name: 'Sputnik',
    description:
      "The lone survivor of an enigmatic spaceship incident hasn't returned home alone - hiding inside his body is a dangerous creature.",
    group: 'Popular Movies',
    type: 'Hulu',
    coverPhoto: 'sputnik.png',
    photo: 'sputnik.jpg',
    releaseYear: 2020,
    imdbRating: 6.4,
  },
  {
    name: 'Transcendence',
    description:
      "A scientist's drive for artificial intelligence takes on dangerous implications when his own consciousness is uploaded into one such program.",
    group: 'Popular Movies',
    type: 'Technology',
    coverPhoto: 'transcendence.jpg',
    photo: 'transcendence.jpg',
    releaseYear: 2014,
    imdbRating: 6.2,
  },
  {
    name: 'Joker',
    description:
      'A mentally troubled stand-up comedian embarks on a downward spiral that leads to the creation of an iconic villain.',
    group: 'Popular Movies',
    type: 'Hollywood',
    coverPhoto: 'joker.jpg',
    photo: 'joker.jpg',
    releaseYear: 2019,
    imdbRating: 8.4,
  },
  {
    name: 'Doctor Strange in the Multiverse of Madness',
    description:
      'Doctor Strange teams up with a mysterious teenage girl from his dreams who can travel across multiverses, to battle multiple threats, including other-universe versions of himself, which threaten to wipe out millions across the multiverse. They seek help from Wanda the Scarlet Witch, Wong and others.',
    group: 'Popular Movies',
    type: 'Marvel',
    coverPhoto: 'multiverseofmadness.jpg',
    photo: 'multiverseofmadness.jpg',
    releaseYear: 2022,
    imdbRating: 7.0,
  },
  {
    name: 'Man of Steel',
    description:
      'An alien child is evacuated from his dying world and sent to Earth to live among humans. His peace is threatened when other survivors of his home planet invade Earth.',
    group: 'Popular Movies',
    type: 'Superhero',
    coverPhoto: 'manofsteel.jpg',
    photo: 'manofsteel.jpg',
    releaseYear: 2013,
    imdbRating: 7.1,
  },
  {
    name: 'Zootopia',
    description:
      'In a city of anthropomorphic animals, a rookie bunny cop and a cynical con artist fox must work together to uncover a conspiracy.',
    group: 'Popular Movies',
    type: 'Disney',
    coverPhoto: 'zootopia.jpg',
    photo: 'zootopia.jpg',
    releaseYear: 2016,
    imdbRating: 8.0,
  },
  {
    name: 'Extraction',
    description:
      "Tyler Rake, a fearless black market mercenary, embarks on the most deadly extraction of his career when he's enlisted to rescue the kidnapped son of an imprisoned international crime lord.",
    group: 'Popular Movies',
    type: 'Netflix',
    coverPhoto: 'extraction.jpg',
    photo: 'extraction.jpg',
    releaseYear: 2020,
    imdbRating: 6.7,
  },
  {
    name: 'Megamind',
    description:
      'Evil genius Megamind finally defeats his do-gooder nemesis, Metro Man, but is left without a purpose in a superhero-free world.',
    group: 'Popular Movies',
    type: 'Animation',
    coverPhoto: 'megamind.jpg',
    photo: 'megamind.jpg',
    releaseYear: 2010,
    imdbRating: 7.3,
  },
];
